BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[LUDI_COMMON_GRADE] (
    [id] INT NOT NULL IDENTITY(1,1),
    [grade_type_name] NVARCHAR(1000) NOT NULL,
    [grade_type_desc] NVARCHAR(1000),
    [created_date] DATETIME2 NOT NULL,
    [modified_date] DATETIME2 NOT NULL,
    CONSTRAINT [LUDI_COMMON_GRADE_pkey] PRIMARY KEY CLUSTERED ([id])
);

-- CreateTable
CREATE TABLE [dbo].[LUDI_COMMON_GRADE_IMAGES] (
    [id] INT NOT NULL IDENTITY(1,1),
    [grade_id] INT NOT NULL,
    [image_url] NVARCHAR(1000) NOT NULL,
    [description] NVARCHAR(1000),
    CONSTRAINT [LUDI_COMMON_GRADE_IMAGES_pkey] PRIMARY KEY CLUSTERED ([id])
);

-- AddForeignKey
ALTER TABLE [dbo].[LUDI_COMMON_GRADE_IMAGES] ADD CONSTRAINT [LUDI_COMMON_GRADE_IMAGES_grade_id_fkey] FOREIGN KEY ([grade_id]) REFERENCES [dbo].[LUDI_COMMON_GRADE]([id]) ON DELETE NO ACTION ON UPDATE CASCADE;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
